import { LegalContact, LegalPage } from "@/components/legal-page";

export const metadata = { title: "Política de privacidad | FocusMRK", description: "Cómo FocusMRK trata la información de cuentas, contenido y reportes, y cómo solicitar su eliminación." };

export default function PrivacyPage() {
  return <LegalPage title="Política de privacidad" intro="Qué información utiliza FocusMRK, para qué la necesita y cómo puedes gestionar tus datos.">
    <section><h2>1. Quién administra el servicio</h2><p>TGX Labs administra FocusMRK en focusmrkt.tgxlabs.io. Esta política describe el tratamiento de información dentro de la plataforma. Cuando una empresa incorpora datos de sus clientes o colaboradores, también es responsable de contar con la autorización correspondiente y de informarles sobre ese uso.</p></section>
    <section><h2>2. Información que utilizamos</h2><ul><li>Datos de acceso y perfil: identificador de cuenta, nombre, credenciales protegidas, sesiones y empresas asignadas.</li><li>Información que incorporas: fichas de empresas, publicaciones, textos, imágenes, videos, enlaces, tareas, cronogramas, métricas y reportes.</li><li>Preferencias técnicas: configuración del navegador, almacenamiento local y, si autorizas notificaciones, la suscripción necesaria para entregarlas.</li><li>Datos técnicos de las solicitudes que pueden procesar los servicios de alojamiento para operar y proteger la plataforma, como dirección IP y registros de errores.</li></ul></section>
    <section><h2>3. Para qué se utiliza</h2><p>Utilizamos la información para autenticar usuarios, aplicar permisos por empresa, guardar y recuperar contenido, generar los documentos solicitados, enviar recordatorios autorizados y resolver incidencias. No utilizamos las métricas de tus redes para dirigir publicidad a sus seguidores.</p></section>
    <section><h2>4. Conexiones con redes sociales</h2><p>La integración automática con TikTok está en preparación. Actualmente, los reportes pueden elaborarse con métricas ingresadas manualmente; esta página no implica que tu cuenta social ya esté conectada.</p><p>Si se habilita una conexión, se solicitará tu autorización en la plataforma correspondiente. Antes de activarla se actualizará esta política para describir los datos y permisos efectivamente utilizados, su conservación y las opciones de desconexión. No debes introducir tu contraseña de TikTok en FocusMRK.</p></section>
    <section><h2>5. Almacenamiento y cookies</h2><p>FocusMRK utiliza una cookie de sesión para mantener el acceso autenticado y almacenamiento del navegador para preferencias y datos locales. En modo local, los archivos pueden guardarse en IndexedDB y otros datos en localStorage; en modo servidor, los datos se guardan en la base de datos del servicio. Borrar los datos del navegador puede eliminar información que solo exista localmente.</p><p>Los archivos que descargas o compartes fuera de FocusMRK quedan bajo tu control. El cierre de sesión no elimina necesariamente los datos locales ni las copias descargadas.</p></section>
    <section><h2>6. Acceso y proveedores</h2><p>Los administradores y usuarios autorizados de tu empresa pueden acceder a los datos de su espacio según sus permisos. Los proveedores de alojamiento, base de datos y entrega de notificaciones pueden procesar la información necesaria para prestar esos servicios. Los enlaces y recursos externos que abras están sujetos a las políticas de sus respectivos proveedores. No vendemos tus datos personales.</p></section>
    <section><h2>7. Conservación y seguridad</h2><p>Conservamos la información mientras sea necesaria para prestar el servicio a la cuenta o empresa, resolver incidencias o atender obligaciones aplicables. Al solicitar una eliminación se revisarán los datos afectados y las posibles obligaciones de conservación; las copias de respaldo pueden requerir un ciclo adicional de renovación antes de desaparecer.</p><p>Se utilizan controles de autenticación y permisos para restringir el acceso. Ningún sistema elimina todos los riesgos: protege tus credenciales y evita guardar información innecesaria o sensible en publicaciones y archivos.</p></section>
    <section><h2>8. Acceso, corrección y eliminación</h2><p>Puedes solicitar acceso, corrección o eliminación de tus datos, así como plantear objeciones sobre su uso o retirar autorizaciones opcionales. Para solicitar la eliminación, identifica tu cuenta y especifica si deseas cerrar el acceso, borrar datos personales o eliminar contenido de una empresa. Verificaremos tu identidad y autorización antes de modificar información compartida.</p><LegalContact /><p>Puedes desactivar las notificaciones desde los permisos del navegador. La eliminación de datos en FocusMRK no borra publicaciones existentes en otras redes ni archivos que ya hayas descargado o compartido.</p></section>
    <section><h2>9. Actualizaciones</h2><p>Publicaremos los cambios en esta página y actualizaremos la fecha. Los cambios sustanciales, incluidas nuevas conexiones que modifiquen el uso de datos, se comunicarán mediante el servicio o el canal de contacto disponible.</p></section>
  </LegalPage>;
}
