import test from "node:test";
import assert from "node:assert/strict";
import { registerHooks } from "node:module";
import { PGlite } from "@electric-sql/pglite";
registerHooks({ resolve(specifier, context, next) {
  if (specifier.startsWith("@/lib/")) return next(new URL(`../lib/${specifier.slice(6)}.ts`, import.meta.url).href, context);
  return next(specifier, context);
} });

test("private PostgreSQL APIs enforce auth, preserve media and reject stale writes", async () => {
  const before = { database: process.env.DATABASE_URL, user: process.env.PANEL_USER, password: process.env.PANEL_PASSWORD };
  process.env.DATABASE_URL = "postgres://test";
  process.env.PANEL_USER = "owner";
  process.env.PANEL_PASSWORD = "test-password-123456789";
  const pg = new PGlite();
  const query = async (sql, params) => {
    if (sql.includes("pg_advisory_xact_lock")) return { rows: [] };
    const result = await pg.query(sql, params);
    return { ...result, rowCount: result.rows.length || result.affectedRows || 0 };
  };
  globalThis.focusPool = { query, connect: async () => ({ query, release() {} }) };
  globalThis.focusSchema = undefined;
  const workspace = await import("../app/api/workspace/route.ts");
  const media = await import("../app/api/media/route.ts");
  const { emptyPublication } = await import("../lib/calendar.ts");
  const headers = { authorization: `Basic ${Buffer.from('owner:test-password-123456789').toString('base64')}`, "x-focusmrk-request": "1" };
  const request = (path, method = "GET", body) => new Request(`http://localhost/api/${path}`, { method, headers, body });
  try {
    assert.equal((await workspace.GET(new Request("http://localhost/api/workspace"))).status, 401);
    const notifications = await import("../app/api/notifications/route.ts");
    assert.equal((await notifications.GET(new Request("http://localhost/api/notifications"))).status, 401);
    const preferences = (await (await notifications.GET(request("notifications"))).json()).settings;
    const tasksApi = await import("../app/api/tasks/route.ts");
    assert.equal((await tasksApi.GET(new Request("http://localhost/api/tasks"))).status, 401);
    const task = { id: "prepare-reel", title: "Preparar reel", date: "2026-09-12", priority: "urgent", postId: "", done: false, snoozedUntil: null, version: 0 };
    const created = await tasksApi.PUT(request("tasks", "PUT", JSON.stringify(task)));
    assert.equal(created.status, 200);
    const savedTask = (await created.json()).task;
    assert.equal(savedTask.version, 1);
    assert.equal((await tasksApi.PUT(request("tasks", "PUT", JSON.stringify(task)))).status, 409);
    assert.equal((await tasksApi.PUT(request("tasks", "PUT", JSON.stringify({ ...savedTask, date: "2026-02-30" })))).status, 400);
    const completed = await tasksApi.PUT(request("tasks", "PUT", JSON.stringify({ ...savedTask, done: true })));
    assert.equal((await completed.json()).task.version, 2);
    assert.equal((await tasksApi.PUT(request("tasks", "PUT", JSON.stringify({ ...savedTask, title: "Stale edit" })))).status, 409);
    const savedTasks = (await (await tasksApi.GET(request("tasks"))).json()).tasks;
    assert.equal(savedTasks[0].done, true);
    assert.equal((await (await notifications.GET(request("notifications"))).json()).health.last_accepted, null);
    assert.equal(preferences.rules.summary.time, "08:00");
    preferences.rules.today.intensity = "intense";
    assert.equal((await notifications.PUT(request("notifications", "PUT", JSON.stringify(preferences)))).status, 200);
    assert.equal((await (await notifications.GET(request("notifications"))).json()).settings.rules.today.intensity, "intense");
    assert.equal((await notifications.PUT(request("notifications", "PUT", JSON.stringify({ ...preferences, end: "07:00" })))).status, 400);
    const state = await (await workspace.GET(request("workspace"))).json();
    assert.deepEqual(state.posts, []);
    const form = new FormData(); form.set("id", "asset"); form.set("brand", "Marca"); form.set("file", new Blob(["abc"], { type: "image/png" }), "image.png");
    assert.equal((await media.POST(request("media", "POST", form))).status, 200);
    const metadataResponse = await media.GET(request("media?id=asset&metadata=1"));
    assert.equal(metadataResponse.headers.get("cache-control"), "no-store");
    const metadata = await metadataResponse.json();
    assert.equal(metadata.id, "asset");
    assert.equal(metadata.size, 3);
    assert.equal((await media.PATCH(new Request("http://localhost/api/media", { method: "PATCH", body: JSON.stringify({ id: "asset", name: "renamed.png" }) }))).status, 401);
    assert.equal((await media.PATCH(request("media", "PATCH", JSON.stringify({ id: "asset", name: "../bad.png" })))).status, 400);
    assert.equal((await media.PATCH(request("media", "PATCH", JSON.stringify({ id: "missing", name: "renamed.png" })))).status, 404);
    assert.equal((await media.PATCH(request("media", "PATCH", JSON.stringify({ id: "asset", name: "renamed.png" })))).status, 200);
    assert.equal((await (await media.GET(request("media?id=asset&metadata=1"))).json()).name, "renamed.png");
    assert.equal(await (await media.GET(request("media?id=asset"))).text(), "abc");
    assert.equal(metadata.data, undefined);
    assert.equal(await (await media.GET(request("media?id=missing&metadata=1"))).json(), null);
    assert.ok((await pg.query("SELECT to_regclass('focus_push_deliveries') AS name")).rows[0].name);
    const post = { ...emptyPublication("2026-09-10"), id: "post", title: "Persistente", mediaId: "asset", objective: "Interacción" };
    const body = JSON.stringify({ version: 0, posts: [post], templates: [] });
    assert.equal((await workspace.PUT(request("workspace", "PUT", body))).status, 200);
    assert.equal((await workspace.PUT(request("workspace", "PUT", body))).status, 409);
    assert.equal((await media.DELETE(request("media?id=asset", "DELETE"))).status, 409);
    const restored = await (await workspace.GET(request("workspace"))).json();
    assert.deepEqual(restored.posts, [post]);
    assert.equal(await (await media.GET(request("media?id=asset"))).text(), "abc");
    assert.equal((await workspace.PUT(request("workspace", "PUT", JSON.stringify({ version: 1, posts: [{ ...post, mediaId: "missing" }], templates: [] })))).status, 400);
    assert.equal((await workspace.PUT(new Request("http://localhost/api/workspace", { method: "PUT", headers: { ...headers, "sec-fetch-site": "cross-site" }, body }))).status, 403);
    assert.equal((await workspace.PUT(request("workspace", "PUT", JSON.stringify({ version: 1, posts: [], templates: [] })))).status, 200);
    assert.equal((await media.DELETE(request("media?id=asset", "DELETE"))).status, 200);
    process.env.PANEL_PASSWORD = "";
    assert.equal((await workspace.GET(request("workspace"))).status, 503);
  } finally {
    for (const [key, value] of Object.entries({ DATABASE_URL: before.database, PANEL_USER: before.user, PANEL_PASSWORD: before.password })) { if (value === undefined) delete process.env[key]; else process.env[key] = value; }
    delete globalThis.focusPool; delete globalThis.focusSchema;
    await pg.close();
  }
});
