import test from "node:test";
import assert from "node:assert/strict";
import { registerHooks } from "node:module";
import { PGlite } from "@electric-sql/pglite";
registerHooks({ resolve(specifier, context, next) {
  if (specifier.startsWith("@/lib/")) return next(new URL(`../lib/${specifier.slice(6)}.ts`, import.meta.url).href, context);
  return next(specifier, context);
} });

test("private PostgreSQL APIs enforce auth, preserve media and reject stale writes", async () => {
  const before = { database: process.env.DATABASE_URL, user: process.env.PANEL_USER, password: process.env.PANEL_PASSWORD };
  process.env.DATABASE_URL = "postgres://test";
  process.env.PANEL_USER = "owner";
  process.env.PANEL_PASSWORD = "test-password-123456789";
  const pg = new PGlite();
  const query = async (sql, params) => {
    if (sql.includes("pg_advisory_xact_lock")) return { rows: [] };
    const result = await pg.query(sql, params);
    return { ...result, rowCount: result.rows.length || result.affectedRows || 0 };
  };
  globalThis.focusPool = { query, connect: async () => ({ query, release() {} }) };
  globalThis.focusSchema = undefined;
  const workspace = await import("../app/api/workspace/route.ts");
  const media = await import("../app/api/media/route.ts");
  const { emptyPublication } = await import("../lib/calendar.ts");
  const headers = { authorization: `Basic ${Buffer.from('owner:test-password-123456789').toString('base64')}`, "x-focusmrk-request": "1" };
  const request = (path, method = "GET", body) => new Request(`http://localhost/api/${path}`, { method, headers, body });
  try {
    assert.equal((await workspace.GET(new Request("http://localhost/api/workspace"))).status, 401);
    const companies = await import("../app/api/companies/route.ts");
    assert.equal((await companies.GET(new Request("http://localhost/api/companies"))).status, 401);
    assert.equal((await companies.POST(request("companies", "POST", JSON.stringify({ name: "" })))).status, 400);
    assert.equal((await companies.POST(request("companies", "POST", JSON.stringify({ name: "Empresa A" })))).status, 200);
    assert.equal((await companies.POST(request("companies", "POST", JSON.stringify({ name: "Empresa A" })))).status, 200);
    assert.deepEqual(await (await companies.GET(request("companies"))).json(), ["Empresa A"]);
    const profiles = await import("../app/api/company-profile/route.ts");
    const { emptyCompanyProfile } = await import("../lib/company-profile.ts");
    assert.equal((await profiles.GET(new Request("http://localhost/api/company-profile?company=Empresa%20A"))).status, 401);
    const profile = { ...emptyCompanyProfile("Nombre nuevo"), instagram: "https://www.instagram.com/empresa/", website: "https://example.com" };
    assert.equal((await profiles.PUT(request("company-profile", "PUT", JSON.stringify({ company: "Empresa A", version: 0, profile })))).status, 200);
    assert.equal((await profiles.PUT(request("company-profile", "PUT", JSON.stringify({ company: "Empresa A", version: 0, profile })))).status, 409);
    assert.equal((await profiles.PUT(request("company-profile", "PUT", JSON.stringify({ company: "Empresa A", version: 1, profile: { ...profile, instagram: "https://instagram.com.evil.test" } })))).status, 400);
    assert.equal((await profiles.PUT(request("company-profile", "PUT", JSON.stringify({ company: "Empresa A", version: 1, profile: { ...profile, logo: "data:image/svg+xml;base64,abcd" } })))).status, 400);
    const storedProfile = await (await profiles.GET(request("company-profile?company=Empresa%20A"))).json();
    assert.equal(storedProfile.profile.name, "Nombre nuevo");
    assert.equal(storedProfile.version, 1);
    const notifications = await import("../app/api/notifications/route.ts");
    assert.equal((await notifications.GET(new Request("http://localhost/api/notifications"))).status, 401);
    const preferences = (await (await notifications.GET(request("notifications"))).json()).settings;
    const tasksApi = await import("../app/api/tasks/route.ts");
    assert.equal((await tasksApi.GET(new Request("http://localhost/api/tasks"))).status, 401);
    const task = { id: "prepare-reel", title: "Preparar reel", date: "2026-09-12", priority: "urgent", postId: "", done: false, snoozedUntil: null, version: 0 };
    const created = await tasksApi.PUT(request("tasks", "PUT", JSON.stringify(task)));
    assert.equal(created.status, 200);
    const savedTask = (await created.json()).task;
    assert.equal(savedTask.version, 1);
    assert.equal((await tasksApi.PUT(request("tasks", "PUT", JSON.stringify(task)))).status, 409);
    assert.equal((await tasksApi.PUT(request("tasks", "PUT", JSON.stringify({ ...savedTask, date: "2026-02-30" })))).status, 400);
    const completed = await tasksApi.PUT(request("tasks", "PUT", JSON.stringify({ ...savedTask, done: true })));
    assert.equal((await completed.json()).task.version, 2);
    assert.equal((await tasksApi.PUT(request("tasks", "PUT", JSON.stringify({ ...savedTask, title: "Stale edit" })))).status, 409);
    const savedTasks = (await (await tasksApi.GET(request("tasks"))).json()).tasks;
    assert.equal(savedTasks[0].done, true);
    assert.equal((await (await notifications.GET(request("notifications"))).json()).health.last_accepted, null);
    assert.equal(preferences.rules.summary.time, "08:00");
    preferences.rules.today.intensity = "intense";
    assert.equal((await notifications.PUT(request("notifications", "PUT", JSON.stringify(preferences)))).status, 200);
    assert.equal((await (await notifications.GET(request("notifications"))).json()).settings.rules.today.intensity, "intense");
    assert.equal((await notifications.PUT(request("notifications", "PUT", JSON.stringify({ ...preferences, end: "07:00" })))).status, 400);
    const state = await (await workspace.GET(request("workspace"))).json();
    assert.deepEqual(state.posts, []);
    const form = new FormData(); form.set("id", "asset"); form.set("brand", "Marca"); form.set("file", new Blob(["abc"], { type: "image/png" }), "image.png");
    assert.equal((await media.POST(request("media", "POST", form))).status, 200);
    const metadataResponse = await media.GET(request("media?id=asset&metadata=1"));
    assert.equal(metadataResponse.headers.get("cache-control"), "no-store");
    const metadata = await metadataResponse.json();
    assert.equal(metadata.id, "asset");
    assert.equal(metadata.size, 3);
    assert.equal((await media.PATCH(new Request("http://localhost/api/media", { method: "PATCH", body: JSON.stringify({ id: "asset", name: "renamed.png" }) }))).status, 401);
    assert.equal((await media.PATCH(request("media", "PATCH", JSON.stringify({ id: "asset", name: "../bad.png" })))).status, 400);
    assert.equal((await media.PATCH(request("media", "PATCH", JSON.stringify({ id: "missing", name: "renamed.png" })))).status, 404);
    assert.equal((await media.PATCH(request("media", "PATCH", JSON.stringify({ id: "asset", name: "renamed.png" })))).status, 200);
    assert.equal((await (await media.GET(request("media?id=asset&metadata=1"))).json()).name, "renamed.png");
    assert.equal(await (await media.GET(request("media?id=asset"))).text(), "abc");
    assert.equal(metadata.data, undefined);
    assert.equal(await (await media.GET(request("media?id=missing&metadata=1"))).json(), null);
    assert.ok((await pg.query("SELECT to_regclass('focus_push_deliveries') AS name")).rows[0].name);
    const post = { ...emptyPublication("2026-09-10"), id: "post", title: "Persistente", mediaId: "asset", objective: "Interacción" };
    const body = JSON.stringify({ version: 0, posts: [post], templates: [] });
    assert.equal((await workspace.PUT(request("workspace", "PUT", body))).status, 200);
    assert.equal((await workspace.PUT(request("workspace", "PUT", body))).status, 409);
    assert.equal((await media.DELETE(request("media?id=asset", "DELETE"))).status, 409);
    const restored = await (await workspace.GET(request("workspace"))).json();
    assert.deepEqual(restored.posts, [post]);
    assert.equal(await (await media.GET(request("media?id=asset"))).text(), "abc");
    assert.equal((await workspace.PUT(request("workspace", "PUT", JSON.stringify({ version: 1, posts: [{ ...post, mediaId: "missing" }], templates: [] })))).status, 400);
    assert.equal((await workspace.PUT(new Request("http://localhost/api/workspace", { method: "PUT", headers: { ...headers, "sec-fetch-site": "cross-site" }, body }))).status, 403);
    assert.equal((await workspace.PUT(request("workspace", "PUT", JSON.stringify({ version: 1, posts: [], templates: [] })))).status, 200);
    assert.equal((await media.DELETE(request("media?id=asset", "DELETE"))).status, 200);
    const { default: migration } = await import("../scripts/lib/manabiche-migration.cjs");
    const client = await globalThis.focusPool.connect();
    await migration.migrate(client, { login: "owner", backupSha256: "b".repeat(64) });
    const me = await import("../app/api/me/route.ts");
    assert.equal((await me.GET(new Request("http://localhost/api/me"))).status, 401);
    assert.equal((await me.PUT(new Request("http://localhost/api/me", { method: "PUT", body: JSON.stringify({ display_name: "Intruder" }) }))).status, 401);
    assert.equal((await me.PUT(new Request("http://localhost/api/me", { method: "PUT", headers: { ...headers, "sec-fetch-site": "cross-site" }, body: JSON.stringify({ display_name: "Intruder" }) }))).status, 403);
    assert.equal((await me.PUT(request("me", "PUT", JSON.stringify({ display_name: "   " })))).status, 400);
    assert.equal((await me.PUT(request("me", "PUT", JSON.stringify({ display_name: "Owner display" })))).status, 200);
    assert.equal((await (await me.GET(request("me"))).json()).account.display_name, "Owner display");
    assert.equal((await me.PATCH(request("me", "PATCH", JSON.stringify({ currentPassword: "test-password-123456789", newPassword: "different-owner-password" })))).status, 409);
    assert.equal(process.env.PANEL_PASSWORD, "test-password-123456789");
    const account = (await (await me.GET(request("me"))).json()).account;
    assert.equal(account.login, "owner"); assert.equal(account.company, "Todas las empresas"); assert.equal(account.role, "administrator");
    assert.equal((await (await workspace.GET(request("workspace"))).json()).companyId, "manabiche");
    const upload = new FormData(); upload.set("id", "new-asset"); upload.set("brand", "Manabiche"); upload.set("file", new Blob(["video-bytes"], { type: "video/mp4" }), "clip.mp4");
    assert.equal((await media.POST(request("media", "POST", upload))).status, 200);
    assert.equal((await pg.query("SELECT company_id FROM focus_media WHERE id = 'new-asset'")).rows[0].company_id, "manabiche");
    assert.equal(await (await media.GET(request("media?id=new-asset"))).text(), "video-bytes");
    const { createMarketingAccount } = await import("../scripts/create-marketing-account.cjs");
    const manager = await createMarketingAccount(client);
    await assert.rejects(createMarketingAccount(client), /ya existe/);
    await assert.rejects(createMarketingAccount(client, "owner"), /distinto/);
    const { accountLogin, panelAccess, revokeAccountSession } = await import("../lib/account-access.ts");
    assert.equal(await accountLogin(manager.login, "wrong-password"), null);
    const token = await accountLogin(manager.login, manager.password);
    assert.ok(token);
    const managerRequest = (path, method = "GET", body) => new Request(`http://localhost/api/${path}`, { method, headers: { cookie: `focusmrk_session=${token}`, "x-focusmrk-request": "1" }, body });
    const identity = (await (await me.GET(managerRequest("me"))).json()).account;
    assert.equal(identity.role, "marketing_manager"); assert.deepEqual(identity.companies, ["Manabiche"]);
    assert.equal(identity.canChangePassword, true);
    assert.equal((await me.PUT(managerRequest("me", "PUT", JSON.stringify({ display_name: "Updated manager", id: "owner", role: "administrator" })))).status, 200);
    const updatedIdentity = (await (await me.GET(managerRequest("me"))).json()).account;
    assert.equal(updatedIdentity.display_name, "Updated manager");
    assert.equal(updatedIdentity.role, "marketing_manager");
    assert.equal((await (await me.GET(request("me"))).json()).account.display_name, "Owner display");
    assert.equal((await me.PATCH(managerRequest("me", "PATCH", JSON.stringify({ currentPassword: manager.password, newPassword: "short" })))).status, 400);
    assert.equal((await me.PATCH(managerRequest("me", "PATCH", JSON.stringify({ currentPassword: "incorrect", newPassword: "different-password-123456" })))).status, 400);
    assert.equal(await accountLogin(manager.login, "different-password-123456"), null);
    assert.equal((await companies.POST(managerRequest("companies", "POST", JSON.stringify({ name: "Other" })))).status, 403);
    assert.equal((await profiles.GET(managerRequest("company-profile?company=Other"))).status, 403);
    assert.equal((await panelAccess(managerRequest("notifications"))).status, 403);
    const ownPost = { ...post, id: "own", brand: "Manabiche", mediaId: "new-asset" };
    const hiddenPost = { ...post, id: "hidden", brand: "Other", mediaId: "" };
    await pg.query("UPDATE focus_panel SET posts = $1::jsonb", [JSON.stringify([ownPost, hiddenPost])]);
    const scoped = await (await workspace.GET(managerRequest("workspace"))).json();
    assert.deepEqual(scoped.posts.map(p => p.id), ["own"]);
    assert.equal((await workspace.PUT(managerRequest("workspace", "PUT", JSON.stringify({ ...scoped, posts: [hiddenPost] })))).status, 403);
    assert.equal((await workspace.PUT(managerRequest("workspace", "PUT", JSON.stringify({ ...scoped, posts: [{ ...ownPost, title: "Updated" }] })))).status, 200);
    const retained = (await pg.query("SELECT posts FROM focus_panel")).rows[0].posts;
    assert.deepEqual(retained.find(p => p.id === "hidden"), hiddenPost);
    assert.equal(retained.find(p => p.id === "own").title, "Updated");
    await pg.query("INSERT INTO focus_media(id,name,brand,type,size,created_at,data) VALUES('private','private.png','Other','image/png',3,now(),$1)", [Buffer.from("abc")]);
    assert.equal((await media.GET(managerRequest("media?id=private"))).status, 404);
    assert.equal((await media.DELETE(managerRequest("media?id=private", "DELETE"))).status, 404);
    assert.equal((await media.PATCH(managerRequest("media", "PATCH", JSON.stringify({ id: "private", name: "changed.png" })))).status, 404);
    assert.deepEqual((await (await media.GET(managerRequest("media"))).json()).map(a => a.id), ["new-asset"]);
    assert.deepEqual((await (await tasksApi.GET(managerRequest("tasks"))).json()).tasks, []);
    await pg.query("UPDATE focus_accounts SET enabled=false WHERE id=$1", [manager.id]);
    assert.equal((await panelAccess(managerRequest("workspace"))).status, 401);
    await pg.query("UPDATE focus_accounts SET enabled=true WHERE id=$1", [manager.id]);
    const secondSession = await accountLogin(manager.login, manager.password);
    const passwordChange = await me.PATCH(managerRequest("me", "PATCH", JSON.stringify({ currentPassword: manager.password, newPassword: "different-password-123456" })));
    assert.equal(passwordChange.status, 200);
    assert.match(passwordChange.headers.get("set-cookie"), /Max-Age=0/);
    assert.equal((await pg.query("SELECT count(*)::int AS count FROM focus_account_sessions WHERE account_id = $1", [manager.id])).rows[0].count, 0);
    assert.equal((await panelAccess(new Request("http://localhost/api/me", { headers: { cookie: `focusmrk_session=${secondSession}` } }))).status, 401);
    assert.equal(await accountLogin(manager.login, manager.password), null);
    const freshToken = await accountLogin(manager.login, "different-password-123456");
    assert.ok(freshToken);
    await revokeAccountSession(new Request("http://localhost/api/auth", { method: "DELETE", headers: { cookie: `focusmrk_session=${freshToken}`, "x-focusmrk-request": "1" } }));
    await revokeAccountSession(managerRequest("auth", "DELETE"));
    assert.equal((await panelAccess(managerRequest("workspace"))).status, 401);
    process.env.PANEL_PASSWORD = "";
    assert.equal((await workspace.GET(request("workspace"))).status, 503);
  } finally {
    for (const [key, value] of Object.entries({ DATABASE_URL: before.database, PANEL_USER: before.user, PANEL_PASSWORD: before.password })) { if (value === undefined) delete process.env[key]; else process.env[key] = value; }
    delete globalThis.focusPool; delete globalThis.focusSchema;
    await pg.close();
  }
});
