"use client";
import Link from "next/link";
import Image from "next/image";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { ArrowLeft, ArrowUpRight, ChartColumn, Download, RefreshCw, FileText } from "lucide-react";
import { CompanySelector } from "../calendar/company-selector";
import { UserProfileMenu } from "../user-profile-menu";
import { Bars, Heatmap, LineChart, formatNumber as fmt } from "./charts";
import { blankNotes, metric, metricLabels, publicationDate, platforms, shiftDate, type ContentReport, type ReportQuery, type SocialPublication, type ReportNotes, type MetricCoverage } from "@/lib/content-reports/model";

const sortOptions = { reach:"Mayor alcance", views:"Más visualizaciones", likes:"Más likes", comments:"Más comentarios", engagement:"Mayor engagement", shares:"Más compartidos", saves:"Más guardados", followersGained:"Más seguidores", recent:"Más recientes" };
const typeNames = { REEL:"Reels", POST:"Posts", CAROUSEL:"Carruseles", STORY:"Historias", VIDEO:"Videos", TIKTOK:"TikToks" };
function initialQuery(): ReportQuery {
  const today = new Intl.DateTimeFormat("en-CA",{timeZone:"America/Guayaquil"}).format(new Date());
  return { companyId:"",platform:"Todas",startDate:shiftDate(today,-29),endDate:today,mode:"production" };
}
async function readResponse(response: Response) { const data = await response.json().catch(()=>{throw new Error(`Respuesta inválida del servidor (HTTP ${response.status}).`);}); if(!response.ok) throw new Error(data?.error || `No se pudo cargar el informe (HTTP ${response.status}).`);return data; }
function queryString(q:ReportQuery) {return new URLSearchParams({...q}).toString();}
function Thumb({post}:{post:SocialPublication}) { return post.thumbnailUrl ? <Image unoptimized src={post.thumbnailUrl} width={80} height={80} alt={post.title} /> : <span className="ci-thumb" aria-label="Miniatura no disponible"><FileText size={24}/></span>; }
function Panel({title,children}:{title:string;children:React.ReactNode}) {return <section className="ci-panel"><h2>{title}</h2>{children}</section>;}
function coverageText(value:MetricCoverage) {
  if(value.availableTotal===null)return "Sin datos recibidos";
  const unit=value.unit==="components"?"valores de interacción":value.unit==="observations"?"observaciones":"publicaciones";
  return value.complete?`${value.availableCount} ${unit} con datos`:`Subtotal · ${value.availableCount} de ${value.totalCount} ${unit} con datos`;
}
function CoverageValue({value}:{value:MetricCoverage}) {return <>{fmt(value.availableTotal)}{value.availableTotal!==null&&!value.complete&&<small>{coverageText(value)}</small>}</>;}

export function ContentReportsDashboard({server,publicationId}:{server:boolean;publicationId?:string}) {
  const router = useRouter();
  const [q,setQuery]=useState<ReportQuery>(initialQuery),[mounted,setMounted]=useState(false),[report,setReport]=useState<ContentReport|null>(null),[error,setError]=useState(""),[loading,setLoading]=useState(false),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[notes,setNotes]=useState<ReportNotes>(blankNotes),[dirty,setDirty]=useState(false),[sort,setSort]=useState("views"),[chartMetric,setChartMetric]=useState("views"),[enabled,setEnabled]=useState<string[]>([...platforms]);
  useEffect(()=>{
    const params=new URLSearchParams(window.location.search),defaults=initialQuery();
    const candidate={...defaults,...Object.fromEntries(["companyId","platform","startDate","endDate","mode"].flatMap(key=>params.has(key)?[[key,params.get(key)!]]:[]))} as ReportQuery;
    const instagram=params.get("instagram"),insights=params.get("instagramInsights");
    const oauthMessage=instagram==="cancelled"?"Autorización de Instagram cancelada. Puedes intentarlo de nuevo.":instagram==="connected"?insights==="granted"?"Instagram autorizó las estadísticas. Pulsa Consultar redes para actualizar el informe.":insights==="not_granted"?"Instagram está conectado, pero no concedió el permiso de estadísticas. Revisa los permisos de la aplicación antes de autorizar de nuevo.":"Instagram está conectado. Pulsa Consultar redes para comprobar el acceso a estadísticas y actualizar el informe.":"";
    const timer = window.setTimeout(()=>{setQuery(candidate);setMounted(true);setLoading(!!candidate.companyId);setMessage(oauthMessage);},0);
    return ()=>clearTimeout(timer);
  },[]);
  const query=queryString(q);
  useEffect(()=>{
    if(!mounted||!q.companyId) return;
    const controller=new AbortController();
    fetch(`/api/reports/summary?${query}`,{cache:"no-store",signal:controller.signal}).then(readResponse).then((data:ContentReport)=>{if(controller.signal.aborted)return;setReport(data);setNotes(data.notes);setDirty(false);}).catch(e=>{if(!controller.signal.aborted)setError(e.message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});
    if(!publicationId) window.history.replaceState(null,"",`/dashboard/informes?${query}`);
    return ()=>controller.abort();
  },[mounted,query,q.companyId,publicationId]);
  useEffect(()=>{if(!dirty)return;const before=(event:BeforeUnloadEvent)=>{event.preventDefault();};window.addEventListener("beforeunload",before);return()=>window.removeEventListener("beforeunload",before);},[dirty]);
  function change(next:Partial<ReportQuery>){if(dirty&&!window.confirm("Hay análisis sin guardar. ¿Descartar los cambios?"))return;setDirty(false);setMessage("");setLoading(!!(next.companyId ?? q.companyId));setError("");setReport(null);setQuery(current=>({...current,...next}));}
  function period(value:string){if(value==="custom")return;const today=initialQuery().endDate,year=Number(today.slice(0,4)),month=Number(today.slice(5,7));let start=shiftDate(today,value==="7"?-6:-29),end=today;if(value==="month")start=today.slice(0,7)+"-01";if(value==="previous"){start=new Date(Date.UTC(year,month-2,1,12)).toISOString().slice(0,10);end=shiftDate(today.slice(0,7)+"-01",-1);}change({startDate:start,endDate:end});}
  async function save(){if(busy)return;setBusy(true);setMessage("");try{if(q.mode==="demo"){setMessage("DEMO: análisis de prueba, no se guarda en producción.");setDirty(false);return;}const data=await readResponse(await fetch(`/api/reports/insights?${query}`,{method:"PUT",headers:{"Content-Type":"application/json","X-FocusMRK-Request":"1"},body:JSON.stringify(notes)}));setNotes({...notes,version:data.version});setDirty(false);setMessage("Análisis y recomendaciones guardados.");}catch(e){setMessage(e instanceof Error?e.message:"No se pudo guardar.");}finally{setBusy(false);}}
  async function sync(){
    if(busy)return;setBusy(true);setMessage("");
    try {
      const response=await fetch(`/api/reports/insights?${query}`,{method:"POST",headers:{"Content-Type":"application/json","X-FocusMRK-Request":"1"}});
      const data=await response.json().catch(()=>{throw new Error(`Respuesta inválida del servidor (HTTP ${response.status}).`);});
      const updated=await readResponse(await fetch(`/api/reports/summary?${query}`,{cache:"no-store"}));setReport(updated);
      const failed=Array.isArray(data.results)?data.results.filter((r:{status:string})=>r.status==="error").length:0;
      setMessage(response.ok?`${data.imported} publicaciones consultadas entre el período seleccionado y el anterior.${failed?` ${failed} red(es) no pudieron actualizarse; revisa el estado de consulta.`:""}`:data.error||"No se pudo actualizar.");
    }catch(e){setMessage(e instanceof Error?e.message:"No se pudo actualizar.");}finally{setBusy(false);}
  }
  async function authorizeMetrics(platform:"Instagram"|"Facebook") {
    if(busy)return;setBusy(true);setMessage("");
    try {
      const path=platform==="Instagram"?"/api/instagram/connect":"/api/meta";
      const params=new URLSearchParams({company:q.companyId,reports:"1"});
      if(platform==="Instagram")params.set("returnTo",`/dashboard/informes?${query}`);
      const data=await readResponse(await fetch(`${path}?${params}`,{method:"POST",headers:{"Content-Type":"application/json","X-FocusMRK-Request":"1"},body:JSON.stringify({action:"connect"})}));
      const url=new URL(data.url),host=platform==="Instagram"?"www.instagram.com":"www.facebook.com";
      if(url.protocol!=="https:"||url.hostname!==host)throw new Error("URL de autorización no válida.");
      window.location.assign(url.href);
    }catch(e){setMessage(e instanceof Error?e.message:"No se pudo iniciar la autorización.");setBusy(false);}
  }
  const sorted=report?[...report.publications].sort((a,b)=>sort==="recent"?b.publishedAt.localeCompare(a.publishedAt):(metric(b,sort)??-1)-(metric(a,sort)??-1)):[];
  const top=sorted.filter(p=>sort==="recent"||metric(p,sort)!==null).slice(0,5);
  const lower=sorted.filter(p=>sort!=="recent" && metric(p,sort)!==null).slice(-5).reverse();
  const selected=report?.publications.find(p=>p.id===publicationId);
  // Fast Refresh can retain an earlier response while the API contract gains
  // coverage fields. Wait for the current request before rendering those fields.
  const reportReady=!!report&&Array.isArray(report.networkSummaries)&&report.comparison.every(k=>!!k.currentCoverage&&!!k.previousCoverage);
  const detailUrl=(p:SocialPublication)=>`/dashboard/informes/publicacion/${encodeURIComponent(p.id)}?${query}`;
  const series=report?platforms.filter(p=>enabled.includes(p)&&(q.platform==="Todas"||q.platform===p)).map(platform=>({name:platform,values:report.series.map(day=>{const row=day.networks.find(n=>n.platform===platform);return row?(row[chartMetric as keyof typeof row] as number|null)??null:null;})})):[];
  return <div className="ci-layout"><aside className="ci-sidebar"><Link className="brand" href="/">focus<span>mrk</span></Link><Link href="/"><ArrowLeft size={18}/> Calendario</Link><Link className="nav-active" href="/dashboard/informes"><ChartColumn size={18}/> Informes de contenido</Link><Link href="/?module=reports">Reportes de TikTok</Link><Link href="/?module=integrations">Integraciones</Link></aside><main className="ci-main"><header className="ci-topbar"><Link href="/">Tu espacio de trabajo</Link><UserProfileMenu server={server} onNotifications={() => { router.push("/?module=day"); }}/></header><div className="ci-content">
    <div className="ci-heading"><div><span className="eyebrow">RESULTADOS QUE CUENTAN UNA HISTORIA</span><h1>{publicationId?"Detalle de publicación":"Informes de contenido"}<span>.</span></h1><p>{publicationId?"Conoce el rendimiento de cada pieza de contenido.":"Explora tus resultados, encuentra patrones y prepara el siguiente período."}</p></div><button className="secondary-button ci-no-print" disabled={!reportReady||loading} onClick={()=>window.print()}><Download size={18}/>Exportar informe</button></div>
    <fieldset disabled={busy} className="ci-filters ci-no-print"><CompanySelector server={server} known={[]} canCreate={false} value={q.companyId} onChange={companyId=>change({companyId})}/><label>Red social<select value={q.platform} onChange={e=>change({platform:e.target.value as ReportQuery["platform"]})}><option>Todas</option>{platforms.map(p=><option key={p}>{p}</option>)}</select></label><label>Período<select defaultValue="30" onChange={e=>period(e.target.value)}><option value="7">Últimos 7 días</option><option value="30">Últimos 30 días</option><option value="month">Mes actual</option><option value="previous">Mes anterior</option><option value="custom">Rango personalizado</option></select></label><label>Desde<input type="date" value={q.startDate} onChange={e=>change({startDate:e.target.value})}/></label><label>Hasta<input type="date" min={q.startDate} value={q.endDate} onChange={e=>change({endDate:e.target.value})}/></label><label>Fuente<select value={q.mode} onChange={e=>change({mode:e.target.value as ReportQuery["mode"]})}><option value="production">Datos reales</option><option value="demo">DEMO · Datos ficticios</option></select></label></fieldset>
    <p className={q.mode==="demo"?"ci-demo":"ci-source"}>{q.mode==="demo"?"DEMO · Todas las cifras son ficticias. No se mezclan con las cuentas conectadas.":"DATOS REALES · Solo métricas recibidas de las cuentas conectadas."} · {q.companyId || "Selecciona una empresa"} · {q.startDate} — {q.endDate}</p>
    <p role="status">{busy?"Procesando…":message}</p>
    {loading&&<p role="status">Cargando informe…</p>}{error&&<p role="alert" className="ci-error">{error}</p>}{!q.companyId&&<Panel title="Elige la empresa"><p>Selecciona un cliente y un período para comenzar. Activa DEMO para explorar todas las secciones.</p></Panel>}
    {report&&!reportReady&&!error&&<p role="status">Cargando la versión actual del informe… Si no carga, recarga la página.</p>}
    {reportReady&&report&&<><details className="ci-notes"><summary>Disponibilidad y lectura de los datos</summary>{report.warnings.map(w=><p key={w}>{w}</p>)}<p>La comparación muestra cifras acumuladas de publicaciones de dos períodos; no diferencias de actividad entre fechas de consulta. Las métricas no disponibles no se convierten en cero.</p></details>
      {publicationId?<><Link href={`/dashboard/informes?${query}`} className="ci-no-print">← Volver al informe</Link>{selected?<PublicationDetail post={selected}/>:<Panel title="Publicación no encontrada"><p>No pertenece a la empresa, red o período seleccionado.</p></Panel>}</>:<>
      {q.mode==="production"&&<><div className="ci-actions ci-no-print"><button className="primary-button" disabled={busy||dirty} onClick={()=>void sync()}><RefreshCw size={18}/>{busy?"Consultando…":q.platform==="Todas"?"Consultar redes":`Consultar ${q.platform}`}</button>{(["Instagram","Facebook"] as const).filter(p=>q.platform==="Todas"||q.platform===p).map(p=><button key={p} className="secondary-button" disabled={busy||dirty} onClick={()=>void authorizeMetrics(p)}>Autorizar métricas de {p}</button>)}<Link href="/?module=integrations">Gestionar conexiones</Link></div><p className="ci-no-print">La consulta actualiza publicaciones y seguidores de las cuentas conectadas. Autoriza las métricas si la red pide permisos adicionales.</p>{report.syncs.length>0&&<Panel title="Estado de la última consulta"><div className="ci-three">{report.syncs.map(s=><article key={s.platform}><h3>{s.platform}</h3><p>{s.status==="success"?`${s.imported} publicaciones consultadas`:"No se pudo actualizar"}</p><p>{new Date(s.capturedAt).toLocaleString("es-EC",{timeZone:"America/Guayaquil"})}</p><p>{s.startDate} — {s.endDate}</p>{s.error&&<p className="ci-error">{s.error}</p>}{s.warnings.length>0&&<details><summary>Disponibilidad de métricas</summary>{s.warnings.map(w=><p key={w}>{w}</p>)}</details>}</article>)}</div></Panel>}</>}
      <div className="ci-kpis">{report.comparison.map(k=><article key={k.key}><span>{k.key==="interactions"&&!k.currentCoverage.complete?"Interacciones registradas":k.label}</span><strong>{fmt(k.currentCoverage.availableTotal)}</strong><small>{coverageText(k.currentCoverage)}</small>{k.currentCoverage.availableTotal!==null&&!k.currentCoverage.complete&&<small>Datos recibidos de: {k.currentCoverage.platforms.join(", ")}</small>}<small className={k.change===null?"":k.change>=0?"ci-positive":"ci-negative"}>{k.change===null?"Comparación no disponible":`${k.change>=0?"↑":"↓"} ${fmt(Math.abs(k.change),"%")} vs período anterior`}</small></article>)}</div>
      <p>Los subtotales suman únicamente los datos recibidos. Las cifras faltantes quedan pendientes y las comparaciones requieren datos completos. Las interacciones registradas incluyen los likes, comentarios, compartidos y guardados recibidos.</p>
      <Panel title="Métricas por red"><div className="ci-table-scroll"><table><thead><tr><th>Red</th>{(["publications","views","reach","likes","comments","shares","saves","clicks"] as const).map(key=><th key={key}>{metricLabels[key]}</th>)}</tr></thead><tbody>{report.networkSummaries.map(network=><tr key={network.platform}><th>{network.platform}</th>{(["publications","views","reach","likes","comments","shares","saves","clicks"] as const).map(key=><td key={key}><CoverageValue value={network.coverage[key]}/></td>)}</tr>)}</tbody></table></div><p>Consulta el estado de cada red y sus avisos de disponibilidad para conocer por qué faltan métricas.</p></Panel>
      <div className="ci-two"><Panel title="Contenido publicado"><strong>{report.publications.length} publicaciones</strong><div className="ci-formats">{report.formats.map(f=><div key={f.type}><strong>{f.count}</strong><span>{typeNames[f.type]}</span></div>)}</div></Panel><Panel title="Qué destaca este período">{top.length?<><h3>{top[0].title}</h3><p>{top[0].platform} · {fmt(metric(top[0],sort),sort==="engagement"?"%":"")} · {sortOptions[sort as keyof typeof sortOptions]}</p><Link href={detailUrl(top[0])}>Explorar publicación <ArrowUpRight size={16}/></Link></>:<p>No hay publicaciones con datos para este criterio. Consulta tus redes o cambia al modo DEMO.</p>}</Panel></div>
      <Panel title="Evolución del rendimiento"><div className="ci-actions ci-no-print"><label>Métrica<select value={chartMetric} onChange={e=>setChartMetric(e.target.value)}>{["reach","impressions","views","interactions","profileVisits","followers"].map(key=><option key={key} value={key}>{key==="followers"?"Seguidores":metricLabels[key as keyof typeof metricLabels]}</option>)}</select></label>{platforms.map(p=><label key={p}><input type="checkbox" checked={enabled.includes(p)} onChange={()=>setEnabled(enabled.includes(p)?enabled.filter(v=>v!==p):[...enabled,p])}/>{p}</label>)}</div><p>{chartMetric==="followers"?"Seguidores registrados en cada fecha de consulta.":"Cifras acumuladas de las publicaciones, agrupadas por su fecha de publicación."}</p><LineChart series={series} labels={report.series.map(s=>s.date)}/></Panel>
      <Panel title="Rendimiento de publicaciones"><div className="ci-actions ci-no-print"><label>Ordenar por<select value={sort} onChange={e=>setSort(e.target.value)}>{Object.entries(sortOptions).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><span>{sorted.length} publicaciones</span></div>{sorted.length?<div className="ci-table-scroll"><table className="ci-publications"><thead><tr>{["Publicación","Fecha","Red / formato","Alcance","Impresiones","Vistas","Likes","Comentarios","Compartidos","Guardados","Visitas perfil","Seguidores","Engagement"].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{sorted.map(p=><tr key={p.id}><td><Link href={detailUrl(p)}><Thumb post={p}/><strong>{p.title}</strong></Link></td><td>{publicationDate(p.publishedAt)}</td><td>{p.platform}<small>{typeNames[p.contentType]}</small></td>{[p.metrics.reach,p.metrics.impressions,p.metrics.views,p.metrics.likes,p.metrics.comments,p.metrics.shares,p.metrics.saves,p.metrics.profileVisits,p.metrics.followersGained].map((v,i)=><td key={i}>{fmt(v)}</td>)}<td>{fmt(p.engagementRate,"%")}</td></tr>)}</tbody></table></div>:<p className="ci-empty">No hay publicaciones importadas en este período.</p>}<p>Engagement = (likes + comentarios + compartidos + guardados) / alcance × 100. Si falta un dato, se muestra No disponible.</p></Panel>
      <Panel title="Mejores contenidos del período"><div className="ci-top-content">{top.map((p,i)=><Link key={p.id} href={detailUrl(p)}><span>{i+1}</span><Thumb post={p}/><div><strong>{p.title}</strong><small>{p.platform} · {fmt(metric(p,sort),sort==="engagement"?"%":"")}</small></div></Link>)}</div>{!top.length&&<p>No disponible para el criterio seleccionado.</p>}<p>El Top 5 utiliza el criterio elegido en la tabla de publicaciones.</p></Panel>
      <div className="ci-two"><Panel title="Rendimiento por formato"><p>Promedio por publicación según el criterio seleccionado.</p><Bars rows={report.formats.filter(f=>f.count>0).map(f=>{const values=report.publications.filter(p=>p.contentType===f.type).map(p=>metric(p,sort));return {label:typeNames[f.type],value:values.every(v=>v!==null)?values.reduce<number>((total,v)=>total+v!,0)/values.length:null};})}/></Panel><Panel title="Contenidos con menor resultado"><div className="ci-top-content">{lower.map(p=><Link key={p.id} href={detailUrl(p)}><Thumb post={p}/><div><strong>{p.title}</strong><small>{p.platform} · {fmt(metric(p,sort),sort==="engagement"?"%":"")}</small></div></Link>)}</div>{!lower.length&&<p>Selecciona una métrica con datos disponibles para comparar el rendimiento.</p>}<p>Un resultado menor no implica que la pieza haya fallado: interpreta su objetivo, formato y tiempo publicado.</p></Panel></div>
      <Panel title="Audiencia">{report.audience.length?report.audience.map(a=><div key={a.platform}><h3>{a.platform} · {a.date}</h3><div className="ci-four"><div><h3>Sexo</h3><Bars rows={a.gender} percent/></div><div><h3>Edad</h3><Bars rows={a.age} percent/></div><div><h3>Ciudades</h3><Bars rows={a.cities} percent/></div><div><h3>Países</h3><Bars rows={a.countries} percent/></div></div><h3>Tipo de audiencia</h3><Bars rows={[{label:"Seguidores",value:a.followersReach},{label:"No seguidores",value:a.nonFollowersReach}]} percent/></div>):<p className="ci-empty">No disponible. Las conexiones actuales no aportan datos demográficos al módulo.</p>}</Panel>
      <Panel title="Horarios con mayor actividad">{report.audience.length?report.audience.map(a=><div key={a.platform}><h3>{a.platform}</h3><Heatmap rows={a.activity}/></div>):<Heatmap rows={[]}/>}</Panel>
      <Panel title="Crecimiento de comunidad"><div className="ci-three">{report.followers.map(f=><article key={`${f.platform}:${f.socialAccountId}`}><h3>{f.platform}</h3><dl>{[["Inicio",f.initial],["Final",f.final],["Ganados",f.gained],["Perdidos",f.lost],["Crecimiento neto",f.net]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{fmt(value as number|null)}</dd></div>)}</dl><p>{fmt(f.change,"%")} de crecimiento</p><p>Observaciones: {f.initialDate || "No disponible"} → {f.finalDate || "No disponible"}</p></article>)}</div><LineChart labels={report.series.map(s=>s.date)} series={report.followers.map(f=>({name:`${f.platform} ${report.followers.filter(v=>v.platform===f.platform).length>1?f.socialAccountId.slice(-4):""}`,values:report.series.map(s=>f.series.find(v=>v.date===s.date)?.followers??null)}))}/><p>Sin observaciones históricas no se reconstruye el crecimiento. Ganados y perdidos requieren datos separados.</p></Panel>
      <Panel title="Comparación con período anterior"><p>{report.prior.startDate} — {report.prior.endDate} frente a {q.startDate} — {q.endDate}</p><div className="ci-table-scroll"><table><thead><tr><th>Métrica</th><th>Anterior</th><th>Actual</th><th>Variación</th></tr></thead><tbody>{report.comparison.map(k=><tr key={k.key}><td>{k.label}</td><td><CoverageValue value={k.previousCoverage}/></td><td><CoverageValue value={k.currentCoverage}/></td><td className={k.change!==null&&k.change<0?"ci-negative":"ci-positive"}>{fmt(k.change,"%")}</td></tr>)}</tbody></table></div><p>Los subtotales incompletos se identifican y no generan una variación porcentual.</p></Panel>
      <Panel title="Orgánico vs pagado"><div className="ci-two"><div><h3>Orgánico</h3><dl>{["reach","impressions","interactions","followersGained","clicks"].map(key=><div key={key}><dt>{metricLabels[key as keyof typeof metricLabels]}</dt><dd>{fmt(report.organic[key as keyof typeof report.organic])}</dd></div>)}</dl></div><div><h3>Pagado{report.ads.currency?` · ${report.ads.currency}`:""}</h3><dl>{Object.entries({spend:"Inversión",reach:"Alcance",impressions:"Impresiones",clicks:"Clics",cpm:"CPM",cpc:"CPC",ctr:"CTR",conversions:"Conversiones",messages:"Mensajes",costPerResult:"Costo por resultado"}).map(([key,label])=><div key={key}><dt>{label}</dt><dd>{fmt(report.ads[key as keyof typeof report.ads] as number|null,key==="ctr"?"%":"")}</dd></div>)}</dl></div></div>{report.unknownDistribution>0&&<p>{report.unknownDistribution} publicaciones sin clasificación orgánica/pagada. No se asignan automáticamente a ninguna categoría.</p>}</Panel>
      <Panel title="Análisis del período"><div className="ci-two">{[["worked","Qué funcionó"],["improve","Qué no funcionó"]].map(([key,label])=><label key={key}>{label}<textarea rows={5} maxLength={5000} value={notes[key as "worked"|"improve"]} onChange={e=>{setNotes({...notes,[key]:e.target.value});setDirty(true);}}/></label>)}</div><label>Recomendaciones para el siguiente período<textarea rows={5} maxLength={5000} value={notes.recommendations} onChange={e=>{setNotes({...notes,recommendations:e.target.value});setDirty(true);}}/></label><div className="ci-actions ci-no-print"><button className="primary-button" disabled={!dirty||busy} onClick={()=>void save()}>{q.mode==="demo"?"Revisar análisis de prueba":"Guardar análisis"}</button><span>{dirty?"Cambios sin guardar":"Sin cambios pendientes"}</span></div><div className="ci-print-only"><h3>Qué funcionó</h3><p>{notes.worked || "Sin análisis"}</p><h3>Qué no funcionó</h3><p>{notes.improve || "Sin análisis"}</p><h3>Recomendaciones</h3><p>{notes.recommendations || "Sin recomendaciones"}</p></div><p>Conclusiones manuales. La generación mediante IA se incorporará posteriormente.</p></Panel>
      </>}
    </>}
  </div></main></div>;
}

function PublicationDetail({post:p}:{post:SocialPublication}) {
  return <><Panel title={p.title}><div className="ci-detail"><div className="ci-media-preview">{p.mediaUrl ? ["REEL","TIKTOK","VIDEO"].includes(p.contentType) && !p.mediaUrl.endsWith(".svg") ? <video controls preload="metadata" poster={p.thumbnailUrl || undefined} src={p.mediaUrl}/> : <Image unoptimized src={p.mediaUrl} alt={p.title} width={480} height={480}/> : <p>Imagen o video no disponible</p>}</div><div><p>{p.platform} · {typeNames[p.contentType]} · {publicationDate(p.publishedAt)}</p><p>{p.caption||"Copy no disponible"}</p><p>Campaña: {p.campaignId||"No disponible"}</p>{p.permalink&&/^https:\/\//.test(p.permalink)&&<a href={p.permalink} target="_blank" rel="noopener noreferrer">Abrir publicación ↗</a>}<p>Última consulta: {p.capturedAt}</p></div></div></Panel><Panel title="Métricas principales"><div className="ci-kpis">{Object.entries({reach:"Alcance",impressions:"Impresiones",views:"Visualizaciones",likes:"Likes",comments:"Comentarios",shares:"Compartidos",saves:"Guardados",clicks:"Clics",profileVisits:"Visitas al perfil",followersGained:"Seguidores generados"}).map(([key,label])=><article key={key}><span>{label}</span><strong>{fmt(metric(p,key))}</strong></article>)}<article><span>Engagement</span><strong>{fmt(metric(p,"engagement"),"%")}</strong></article></div></Panel>{["REEL","TIKTOK","VIDEO"].includes(p.contentType)&&<Panel title="Métricas de video"><div className="ci-kpis">{Object.entries({views:"Reproducciones",totalWatchTime:"Tiempo total (s)",averageWatchTime:"Tiempo promedio (s)",duration:"Duración (s)",averageWatchPercentage:"Porcentaje promedio visto",completePlays:"Reproducciones completas"}).map(([key,label])=><article key={key}><span>{label}</span><strong>{fmt(metric(p,key),key==="averageWatchPercentage"?"%":"")}</strong></article>)}</div><h3>Retención</h3><Bars rows={p.metrics.retention} percent/><LineChart labels={p.metrics.retention.map(r=>r.label)} series={[{name:"Retención (%)",values:p.metrics.retention.map(r=>r.value)}]}/></Panel>}</>;
}

