"use client";
import { useEffect, useRef, useState } from "react";
import { availabilityLabels, categoryLabels, metricRegistry, objectiveLabels, officialSources, type Editorial, type ManualMetric, type MetricDatum, type ReportGoal } from "@/lib/content-reports/hybrid";
import type { ExecutiveReport } from "@/lib/content-reports/executive";
import { formatNumber as fmt } from "./charts";

export function SourceBadge({datum}:{datum:Pick<MetricDatum,"source"|"status">}) {return <small className={`ci-badge ci-source-${datum.source.toLowerCase()}`}>{datum.source==="MISSING"?availabilityLabels[datum.status]:{API:"API",MANUAL:"Manual",CALCULATED:"Calculado"}[datum.source]}</small>;}
async function write(path:string,method:string,body:unknown) {const r=await fetch(path,{method,headers:{"Content-Type":"application/json","X-FocusMRK-Request":"1"},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw new Error(data.error||"No se pudo guardar.");return data;}
type Pending = ExecutiveReport["executive"]["pending"][number];
export function ManualDataPanel({report,query,onRefresh,onBusy}:{report:ExecutiveReport;query:string;onRefresh:()=>Promise<void>;onBusy:(value:boolean)=>void}) {
  const e=report.executive,[entry,setEntry]=useState<Partial<ManualMetric>|null>(null),[error,setError]=useState(""),[history,setHistory]=useState<{action:string;actor:string;created_at:string;note:string;before_value:{value:number;preference:string}|null;after_value:{value:number;preference:string}|null}[]|null>(null),[pendingPage,setPendingPage]=useState(0),[platformFilter,setPlatformFilter]=useState("Todas");
  const [working,setWorking]=useState(false);const dialog=useRef<HTMLDialogElement>(null);
  useEffect(()=>{if(entry&&!dialog.current?.open)dialog.current?.showModal();},[entry]);
  useEffect(()=>{
    if(!entry)return;
    const before=(event:BeforeUnloadEvent)=>event.preventDefault();
    const navigate=(event:Event)=>{if(working||!window.confirm("Hay una carga manual abierta. ¿Descartar sus cambios?"))event.preventDefault();};
    window.addEventListener("beforeunload",before);window.addEventListener("focusmrk-before-navigation",navigate);
    return ()=>{window.removeEventListener("beforeunload",before);window.removeEventListener("focusmrk-before-navigation",navigate);};
  },[entry,working]);
  function start(row?:Pending){setError("");setHistory(null);setEntry(row?{platform:row.platform,metric:row.key,level:row.level,publicationId:row.publicationId,socialAccountId:row.level==="ACCOUNT"?row.socialAccountId:null,periodStart:report.query.startDate,periodEnd:report.query.endDate,unit:metricRegistry[row.key]?.unit||"count",officialSource:officialSources[row.platform][0],dataDate:report.query.endDate,note:"",preference:"API",version:0}:{platform:report.query.platform==="Todas"?"Instagram":report.query.platform,metric:"views",level:"PERIOD",publicationId:null,socialAccountId:null,periodStart:report.query.startDate,periodEnd:report.query.endDate,unit:"count",officialSource:officialSources[report.query.platform==="Todas"?"Instagram":report.query.platform][0],dataDate:report.query.endDate,note:"",preference:"API",version:0});}
  async function perform(action:()=>Promise<unknown>){if(working)return;setWorking(true);onBusy(true);setError("");try{await action();await onRefresh();return true;}catch(err){setError((err as Error).message);return false;}finally{setWorking(false);onBusy(false);}}
  const pending=e.pending.filter(row=>platformFilter==="Todas"||row.platform===platformFilter),page=pending.slice(pendingPage*8,pendingPage*8+8);
  return <div className="ci-no-print"><div className="ci-actions"><strong>Datos pendientes · {pending.length} métricas verificables</strong><button className="secondary-button" disabled={report.query.mode==="demo"||working} onClick={()=>start()}>Agregar dato manual</button><label>Red<select value={platformFilter} onChange={event=>{setPlatformFilter(event.target.value);setPendingPage(0);}}><option>Todas</option>{["Instagram","Facebook","TikTok"].map(p=><option key={p}>{p}</option>)}</select></label></div>
    <p>Solo se ofrecen métricas admitidas para carga desde un panel oficial. Las métricas no soportadas sin una fuente verificable no cuentan como pendientes.</p>
    <div className="ci-pending-list">{page.map((row,index)=><div key={`${row.platform}:${row.key}:${row.publicationId||row.socialAccountId}:${index}`}><div><strong>{row.platform} · {metricRegistry[row.key]?.label||row.key}</strong><small>{"title" in row?row.title:"Informe del período"} · {row.datum.reason}</small></div><button className="secondary-button" disabled={report.query.mode==="demo"||working} onClick={()=>start(row)}>Agregar</button></div>)}</div>{pending.length>8&&<div className="ci-actions"><button className="secondary-button" disabled={!pendingPage} onClick={()=>setPendingPage(p=>p-1)}>Anterior</button><span>{pendingPage+1} / {Math.ceil(pending.length/8)}</span><button className="secondary-button" disabled={(pendingPage+1)*8>=pending.length} onClick={()=>setPendingPage(p=>p+1)}>Siguiente</button></div>}
    <details className="ci-manual-records"><summary>Datos manuales y decisiones de origen · {e.manualMetrics.length}</summary>{e.manualMetrics.map(m=>{const datum=m.level==="PUBLICATION"?report.publications.find(p=>p.id===m.publicationId)?.metricData[m.metric]:m.level==="PERIOD"?e.networks.find(n=>n.platform===m.platform)?.metrics[m.metric]?.components[0]?.datum:undefined;return <div className="ci-manual-record" key={m.id}><strong>{m.platform} · {metricRegistry[m.metric]?.label} · {fmt(m.value)} {m.unit==="currency"?"":m.unit}</strong><p>{m.level} · {m.officialSource} · {m.dataDate} · {m.note}</p>{datum?.apiValue!=null&&<div className="ci-data-comparison"><p>Dato automático: <strong>{fmt(datum.apiValue)}</strong> · Manual existente: <strong>{fmt(m.value)}</strong></p><div className="ci-actions"><button className="secondary-button" disabled={working} onClick={()=>void perform(()=>write(`/api/reports/manual-metrics?${query}`,"PUT",{...m,preference:"API",verified:true}))}>Usar automático</button><button className="secondary-button" disabled={working} onClick={()=>void perform(()=>write(`/api/reports/manual-metrics?${query}`,"PUT",{...m,preference:"MANUAL",verified:true}))}>Mantener manual</button><span>Comparación: {fmt(m.value-datum.apiValue)} de diferencia</span></div></div>}<small>Registrado por {m.enteredBy}; última corrección por {m.updatedBy} · v{m.version}</small><div className="ci-actions"><button className="secondary-button" disabled={working} onClick={()=>{setEntry(m);setHistory(null);setError("");}}>Editar</button><button className="secondary-button" disabled={working} onClick={()=>void perform(()=>write(`/api/reports/manual-metrics?${query}`,"DELETE",{id:m.id,version:m.version}))}>Eliminar dato manual</button><button className="secondary-button" onClick={async()=>{try{const r=await fetch(`/api/reports/manual-metrics?${query}&id=${encodeURIComponent(m.id)}`);const data=await r.json();if(!r.ok)throw new Error(data.error);setHistory(data.history);}catch(err){setError((err as Error).message);}}}>Ver historial</button></div></div>;})}</details>
    {history&&<details open><summary>Historial de cambios</summary><div className="ci-audit">{history.map((event,index)=><article key={index}><strong>{({CREATE:"Registro",UPDATE:"Correcci\u00f3n",DELETE:"Eliminaci\u00f3n recuperable",SOURCE_DECISION:"Decisi\u00f3n de origen"})[event.action as "CREATE"]||event.action}</strong><p>{fmt(event.before_value?.value)} → {fmt(event.after_value?.value)} · {event.actor} · {new Date(event.created_at).toLocaleString("es-EC")}</p><p>{event.note}</p>{event.action==="SOURCE_DECISION"&&<p>{event.before_value?.preference} → {event.after_value?.preference}</p>}</article>)}</div></details>}{error&&<p role="alert" className="ci-error">{error}</p>}
    <dialog ref={dialog} className="ci-dialog" onCancel={event=>{if(working)event.preventDefault();else setEntry(null);}} onClose={()=>{if(!working)setEntry(null);}}>{entry&&<form onSubmit={async event=>{event.preventDefault();const form=new FormData(event.currentTarget);const success=await perform(()=>write(`/api/reports/manual-metrics?${query}`,entry.id?"PUT":"POST",{...entry,value:Number(form.get("value")),note:form.get("note"),dataDate:form.get("dataDate"),unit:form.get("unit"),officialSource:form.get("officialSource"),preference:form.get("preference"),verified:form.get("verified")==="on"}));if(success){dialog.current?.close();setEntry(null);}}}><h2>{entry.id?"Corregir dato manual":"Agregar dato manual"}</h2><p>Confirma el valor en el panel oficial. La API conserva su dato original; la decisión de origen queda registrada.</p><fieldset disabled={working}><div className="ci-two"><label>Plataforma<select required disabled={!!entry.id} value={entry.platform} onChange={event=>setEntry({...entry,platform:event.target.value as ManualMetric["platform"],socialAccountId:null,publicationId:null,officialSource:officialSources[event.target.value as ManualMetric["platform"]][0]})}>{["Instagram","Facebook","TikTok"].map(p=><option key={p}>{p}</option>)}</select></label><label>Métrica<select required disabled={!!entry.id} value={entry.metric} onChange={event=>{const def=metricRegistry[event.target.value];setEntry({...entry,metric:event.target.value,unit:def.unit,level:def.levels[0],socialAccountId:null,publicationId:null});}}>{Object.entries(metricRegistry).filter(([,d])=>d.manualEntryAllowed).map(([key,d])=><option value={key} key={key}>{d.label}</option>)}</select></label><label>Nivel<select required disabled={!!entry.id} value={entry.level} onChange={event=>setEntry({...entry,level:event.target.value as ManualMetric["level"],socialAccountId:null,publicationId:null})}>{metricRegistry[entry.metric!]?.levels.map(level=><option key={level}>{level}</option>)}</select></label><label>Período<input readOnly value={`${entry.periodStart} — ${entry.periodEnd}`}/></label></div>
      {entry.level==="PUBLICATION"&&<label>Publicación<select required disabled={!!entry.id} value={entry.publicationId||""} onChange={event=>setEntry({...entry,publicationId:event.target.value})}><option value="">Seleccionar publicación</option>{report.publications.filter(p=>p.platform===entry.platform).map(p=><option key={p.id} value={p.id}>{p.shortTitle}</option>)}</select></label>}
      {entry.level==="ACCOUNT"&&<label>Cuenta<select required disabled={!!entry.id} value={entry.socialAccountId||""} onChange={event=>setEntry({...entry,socialAccountId:event.target.value})}><option value="">Seleccionar cuenta</option>{e.accounts.filter(a=>a.platform===entry.platform).map(a=><option key={a.id} value={a.id}>{a.id}</option>)}</select></label>}
      <div className="ci-two"><label>Valor<input name="value" required type="number" min={metricRegistry[entry.metric!]?.signed?undefined:0} max={metricRegistry[entry.metric!]?.unit==="percent"?100:undefined} step={metricRegistry[entry.metric!]?.unit==="count"?1:"any"} defaultValue={entry.value}/></label><label>Unidad<input required name="unit" readOnly={metricRegistry[entry.metric!]?.unit!=="currency"} defaultValue={entry.unit==="currency"?"USD":entry.unit} key={entry.unit}/></label><label>Fecha del dato<input required type="date" name="dataDate" defaultValue={entry.dataDate}/></label><label>Fuente oficial<select name="officialSource" defaultValue={entry.officialSource} key={entry.platform}>{officialSources[entry.platform!].map(source=><option key={source}>{source}</option>)}</select></label></div><label>Nota<textarea name="note" maxLength={2000} defaultValue={entry.note} placeholder="Tomado del panel oficial; incluye contexto o evidencia verificable."/></label><label>Prioridad cuando la API entregue el dato<select name="preference" defaultValue={entry.preference}><option value="API">Usar automático (conservar registro manual)</option><option value="MANUAL">Mantener manual (registrar decisión)</option></select></label><label className="ci-checkbox"><input type="checkbox" name="verified" required/>He verificado el valor, nivel y período en el panel oficial.</label><div className="ci-actions"><button className="secondary-button" type="button" onClick={()=>dialog.current?.close()}>Cancelar</button><button className="primary-button" type="submit">{working?"Guardando…":"Guardar dato"}</button></div></fieldset></form>}</dialog>
  </div>;
}
export function ClassificationEditor({publicationId,editorial,query,onRefresh,onBusy}:{publicationId:string;editorial:Editorial;query:string;onRefresh:()=>Promise<void>;onBusy:(b:boolean)=>void}) {
  const [error,setError]=useState(""),[busy,setBusy]=useState(false);
  return <form className="ci-no-print" key={editorial.version} onSubmit={async event=>{event.preventDefault();const form=new FormData(event.currentTarget);setBusy(true);onBusy(true);try{await write(`/api/reports/classification?${query}`,"PUT",{publicationId,contentCategory:form.get("category")||null,contentObjective:form.get("objective")||null,version:editorial.version});await onRefresh();setError("");}catch(err){setError((err as Error).message);}finally{setBusy(false);onBusy(false);}}}><h3>Clasificación editorial manual</h3><fieldset disabled={busy}><div className="ci-two"><label>Categoría<select name="category" defaultValue={editorial.contentCategory||""}><option value="">Sin clasificar</option>{Object.entries(categoryLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>Objetivo<select name="objective" defaultValue={editorial.contentObjective||""}><option value="">Sin objetivo</option>{Object.entries(objectiveLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label></div><button className="secondary-button" type="submit">Guardar clasificación</button></fieldset>{error&&<p role="alert">{error}</p>}</form>;
}
export function GoalEditor({report,query,onRefresh,onBusy}:{report:ExecutiveReport;query:string;onRefresh:()=>Promise<void>;onBusy:(b:boolean)=>void}) {
  const [editing,setEditing]=useState<ReportGoal|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false);
  const month=report.query.startDate.slice(0,7);
  return <details className="ci-no-print"><summary>Configurar objetivos mensuales</summary><p>Los objetivos se aplican al mes y red seleccionados. No se reparte una meta mensual entre rangos personalizados.</p><div className="ci-actions">{report.executive.goals.map(goal=><button className="secondary-button" key={goal.id} onClick={()=>setEditing(goal)}>Editar {metricRegistry[goal.metric]?.label}</button>)}<button className="secondary-button" onClick={()=>setEditing(null)}>Nuevo objetivo</button></div><form key={editing?.id||"new"} onSubmit={async event=>{event.preventDefault();const f=new FormData(event.currentTarget);const selected=String(f.get("month"));const start=selected+"-01",end=new Date(Date.UTC(Number(selected.slice(0,4)),Number(selected.slice(5,7)),0,12)).toISOString().slice(0,10);setBusy(true);onBusy(true);setError("");try{await write(`/api/reports/goals?${query}`,editing?"PUT":"POST",{id:editing?.id,platform:report.query.platform,periodStart:start,periodEnd:end,metric:f.get("metric"),targetValue:Number(f.get("target")),version:editing?.version||0});await onRefresh();setEditing(null);}catch(err){setError((err as Error).message);}finally{setBusy(false);onBusy(false);}}}><fieldset disabled={busy||report.query.mode==="demo"}><div className="ci-three"><label>Mes<input required name="month" type="month" readOnly={!!editing} defaultValue={editing?.periodStart.slice(0,7)||month}/></label><label>Métrica<select name="metric" disabled={!!editing} defaultValue={editing?.metric||"views"}>{["views","reach","interactions","followersGained","netFollowerGrowth","clicks","messages","publications"].map(key=><option key={key} value={key}>{metricRegistry[key].label}</option>)}</select>{editing&&<input type="hidden" name="metric" value={editing.metric}/>}</label><label>Meta<input required name="target" type="number" min={1} step={1} defaultValue={editing?.targetValue}/></label></div><button type="submit" className="secondary-button">Guardar objetivo</button></fieldset>{error&&<p role="alert">{error}</p>}</form></details>;
}
