import { LegalContact, LegalPage } from "@/components/legal-page";
import Link from "next/link";

export const metadata = { title: "Términos de uso | FocusMRK", description: "Condiciones de acceso y uso de FocusMRK, la plataforma de planificación de contenido de TGX Labs." };

export default function TermsPage() {
  return <LegalPage title="Términos de uso" intro="Las condiciones para organizar tu contenido y trabajar con tu equipo en FocusMRK.">
    <section><h2>1. El servicio</h2><p>FocusMRK es una plataforma administrada por TGX Labs para organizar publicaciones, archivos, tareas, cronogramas y reportes de redes sociales. Estas condiciones se aplican al uso de focusmrkt.tgxlabs.io. Al utilizar el servicio aceptas estas condiciones; si no estás de acuerdo, deja de utilizarlo.</p><p>El acceso se habilita por el administrador y puede limitarse a determinadas empresas y funciones. Cualquier condición comercial específica se acuerda por separado.</p></section>
    <section><h2>2. Tu cuenta y tus permisos</h2><p>Debes utilizar credenciales propias, mantenerlas protegidas y acceder únicamente a empresas y datos para los que tengas autorización. Comunica cualquier acceso no autorizado a TGX Labs. Si actúas en nombre de una empresa, debes contar con su autorización.</p></section>
    <section><h2>3. Contenido y uso permitido</h2><p>Conservas los derechos sobre el contenido que incorporas. Autorizas su almacenamiento, procesamiento y presentación únicamente para prestar el servicio, incluidos los documentos que solicites generar. Debes contar con los derechos y permisos necesarios para cargar imágenes, videos y datos de otras personas.</p><p>No está permitido utilizar FocusMRK para actividades ilícitas, suplantar identidades, distribuir contenido malicioso, acceder a información ajena o interferir con la seguridad y disponibilidad del servicio.</p></section>
    <section><h2>4. Redes sociales y reportes</h2><p>Actualmente, la planificación y los reportes pueden utilizar datos ingresados manualmente. Crear una publicación en el calendario no implica publicarla automáticamente en una red social.</p><p>Las conexiones con plataformas externas solo estarán disponibles cuando se habiliten y autorices los permisos correspondientes. Su disponibilidad depende de cada proveedor y de sus condiciones. FocusMRK no es un producto oficial de TikTok, Meta ni de las otras redes mencionadas.</p><p>Revisa las fechas, cifras y contenido antes de compartir un reporte. Las métricas pueden tener definiciones distintas por plataforma; no se garantiza un resultado comercial, alcance o crecimiento determinado.</p></section>
    <section><h2>5. Disponibilidad y responsabilidad</h2><p>El servicio puede interrumpirse por mantenimiento, incidencias técnicas o cambios de proveedores. Mantén copias de los contenidos y documentos importantes. TGX Labs atenderá las incidencias comunicadas por sus canales de contacto. Estas condiciones no excluyen derechos ni responsabilidades que no puedan limitarse conforme a la normativa aplicable.</p></section>
    <section><h2>6. Suspensión y finalización</h2><p>El acceso puede suspenderse por uso indebido, riesgos de seguridad o finalización de la autorización de tu empresa. Puedes solicitar el cierre de tu cuenta y la eliminación de tus datos. La información compartida de una empresa requiere verificar quién está autorizado para disponer de ella.</p></section>
    <section><h2>7. Privacidad y cambios</h2><p>El tratamiento de información se describe en la <Link href="/privacidad">Política de privacidad</Link>. Las actualizaciones de estas condiciones se publicarán en esta página con su fecha. Los cambios sustanciales se comunicarán mediante el servicio o el canal de contacto disponible.</p></section>
    <section><h2>8. Contacto</h2><LegalContact /></section>
  </LegalPage>;
}
