"use client";
import { useEffect, useState, type FormEvent } from "react";
import { Check, Plus, Sunrise, Clock3, Pencil, RotateCcw, ArrowUpRight } from "lucide-react";
import { nextDay, zonedDay, type Task } from "@/lib/tasks";
import type { Publication } from "@/lib/calendar";
import type { useTasks } from "./use-tasks";

const priorities = { normal: "Normal", important: "Importante", urgent: "Prioritaria" };
export function MyDay({ store, posts, timezone, server, onOpenPost, onSettings }: { store: ReturnType<typeof useTasks>; posts: Publication[]; timezone: string; server: boolean; onOpenPost: (post: Publication) => void; onSettings: () => void }) {
  const [now, setNow] = useState(() => Date.now());
  useEffect(() => { const tick = setInterval(() => setNow(Date.now()), 30000); return () => clearInterval(tick); }, []);
  const today = zonedDay(new Date(now), timezone);
  const [filter, setFilter] = useState("today");
  const [draft, setDraft] = useState<Task | null>(null);
  const [notice, setNotice] = useState("");
  const score = { urgent: 0, important: 1, normal: 2 };
  const pending = store.tasks.filter(t => !t.done && t.date <= today);
  const items = store.tasks.filter(t => filter === "done" ? t.done : !t.done && (filter === "future" ? t.date > today : t.date <= today)).sort((a,b) => score[a.priority] - score[b.priority] || a.date.localeCompare(b.date) || a.title.localeCompare(b.title));
  const publications = posts.filter(p => p.date <= today && p.status !== "Publicado");
  async function update(task: Task, message: string) { if (await store.save(task)) setNotice(message); }
  async function submit(e: FormEvent) { e.preventDefault(); if (draft && await store.save({ ...draft, title: draft.title.trim() })) { setDraft(null); setNotice("Tarea guardada."); } }
  return <div className="page-content my-day"><div className="page-heading"><div><span className="eyebrow">UN PASO A LA VEZ · {today.split("-").reverse().join("/")}</span><h1>Mi día<span>.</span></h1><p>Prepara hoy lo que vas a publicar mañana. Horarios de {timezone}.</p></div><button className="primary-button" disabled={!store.ready || store.busy} onClick={() => setDraft({ id: crypto.randomUUID(), title: "", date: today, priority: "normal", postId: "", done: false, snoozedUntil: null, version: 0 })}><Plus size={18} />Nueva tarea</button></div>
    <div className="day-overview"><Sunrise size={30} /><div><strong>{pending.length ? `${pending.length} tareas pendientes para hoy` : "Tu día tiene espacio para avanzar"}</strong><p>{pending.filter(t => t.priority === "urgent").length} prioritarias · {publications.length} publicaciones por resolver</p></div><button className="secondary-button" onClick={onSettings}>Configurar avisos</button></div>
    {!server && <p className="notification-footnote">Tus tareas se guardan en este navegador. Conecta el servidor para sincronizarlas y recibir avisos con la app cerrada.</p>}
    {store.error && <div role="alert" className="form-error">{store.error} <button className="secondary-button" disabled={store.busy} onClick={() => void store.reload()}>Recargar tareas</button></div>}
    {notice && <p role="status" className="notification-message">{notice}</p>}
    {draft && <form className="day-editor" onSubmit={submit}><h2>{draft.version ? "Editar tarea" : "¿Qué necesitas hacer?"}</h2><fieldset disabled={store.busy}><label>Tarea<input autoFocus required maxLength={200} value={draft.title} onChange={e => setDraft({ ...draft, title: e.target.value })} placeholder="Ej. Escribir el guion del reel" /></label><div className="day-form-row"><label>Fecha de trabajo<input type="date" required value={draft.date} onChange={e => setDraft({ ...draft, date: e.target.value, snoozedUntil: null })} /></label><label>Prioridad<select value={draft.priority} onChange={e => setDraft({ ...draft, priority: e.target.value as Task["priority"] })}>{Object.entries(priorities).map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select></label></div><label>Publicación relacionada (opcional)<select value={draft.postId} onChange={e => setDraft({ ...draft, postId: e.target.value })}><option value="">Tarea independiente</option>{draft.postId && !posts.some(p => p.id === draft.postId) && <option value={draft.postId}>Publicación no disponible</option>}{posts.map(p => <option key={p.id} value={p.id}>{p.date} · {p.title || "Sin título"}</option>)}</select></label><p>Normal: resumen. Importante: hasta 2 seguimientos. Prioritaria: hasta 4. Siempre sujetos al horario y al límite diario.</p><div className="day-actions"><button className="secondary-button" type="button" onClick={() => setDraft(null)}>Cancelar</button><button className="primary-button" type="submit">{store.busy ? "Guardando…" : "Guardar tarea"}</button></div></fieldset></form>}
    <div className="day-tabs" role="group" aria-label="Filtrar tareas">{[["today", "Hoy y atrasadas"], ["future", "Próximas"], ["done", "Completadas"]].map(([key,label]) => <button className="secondary-button" aria-pressed={filter === key} key={key} onClick={() => setFilter(key)}>{label}</button>)}</div>
    {!store.ready && !store.error && <p role="status">Cargando tareas…</p>}
    {store.ready && !items.length && <div className="day-empty"><Check size={28} /><h2>{filter === "today" ? "Sin tareas pendientes" : "No hay tareas en esta vista"}</h2><p>Añade tareas para preparar textos, diseños y revisiones con su propia fecha.</p></div>}
    <div className="day-task-list">{items.map(task => {
      const linked = posts.find(p => p.id === task.postId); const snoozed = task.snoozedUntil && Date.parse(task.snoozedUntil) > now;
      return <article className="day-task" data-priority={task.priority} key={task.id}><div className="day-task-top"><span className="day-priority">{priorities[task.priority]}</span><time>{task.date < today && !task.done ? "Atrasada · " : ""}{task.date.split("-").reverse().join("/")}</time></div><h2>{task.title}</h2>{linked && <button className="day-post-link" onClick={() => onOpenPost(linked)}><ArrowUpRight size={14} />{linked.title} · Publicación: {linked.date}</button>}{snoozed && !task.done && <p className="day-snoozed"><Clock3 size={14} />Avisos pausados hasta {new Intl.DateTimeFormat("es", { timeZone: timezone, dateStyle: "short", timeStyle: "short" }).format(new Date(task.snoozedUntil!))}</p>}<div className="day-actions"><button className="primary-button" disabled={store.busy} onClick={() => void update({ ...task, done: !task.done, snoozedUntil: null }, task.done ? "Tarea reabierta." : "Tarea completada. Se detiene su seguimiento.")}>{task.done ? <RotateCcw size={15} /> : <Check size={15} />}{task.done ? "Reabrir" : "Completar"}</button>{!task.done && <><button className="secondary-button" disabled={store.busy} onClick={() => void update({ ...task, snoozedUntil: new Date(Date.now() + 3600000).toISOString() }, "Avisos pausados durante una hora.")}>Posponer 1 h</button><button className="secondary-button" disabled={store.busy} onClick={() => void update({ ...task, date: nextDay(today), snoozedUntil: null }, "Tarea movida a mañana. La publicación conserva su fecha.")}>Mañana</button>{snoozed && <button className="secondary-button" disabled={store.busy} onClick={() => void update({ ...task, snoozedUntil: null }, "Seguimiento reanudado.")}>Reanudar avisos</button>}</>}<button className="secondary-button" aria-label={`Editar ${task.title}`} disabled={store.busy} onClick={() => setDraft(task)}><Pencil size={15} />Editar / reprogramar</button></div></article>;
    })}</div>
    {!!publications.length && <section className="day-publications"><h2>Publicaciones por resolver</h2><p>Completar una tarea de preparación no marca la publicación como publicada.</p>{publications.map(post => <button key={post.id} className="day-publication" onClick={() => onOpenPost(post)}><span><strong>{post.title || "Sin título"}</strong><small>{post.date} · {post.brand} · {post.status}</small></span><ArrowUpRight size={18} /></button>)}</section>}
  </div>;
}
