"use client";
import { useState } from "react";
import type { TikTokReportSnapshot } from "@/lib/report-visual";

export function ReportDashboard({ data, stale }: { data: TikTokReportSnapshot; stale: boolean }) {
  const [sort, setSort] = useState<"view_count" | "like_count" | "comment_count" | "share_count">("view_count");
  const [search, setSearch] = useState("");
  const sum = (key: typeof sort) => data.videos.every(v => typeof v[key] === "number") ? data.videos.reduce((s, v) => s + v[key]!, 0) : null;
  const views = sum("view_count"), likes = sum("like_count"), comments = sum("comment_count"), shares = sum("share_count");
  const interactions = likes !== null && comments !== null && shares !== null ? likes + comments + shares : null;
  const fmt = (n: number | null | undefined) => typeof n === "number" ? n.toLocaleString("es") : "No disponible";
  const ranked = [...data.videos].filter(v => (v.title || "").toLocaleLowerCase().includes(search.toLocaleLowerCase())).sort((a, b) => (b[sort] ?? -1) - (a[sort] ?? -1));
  const top = ranked.slice(0, 5), max = Math.max(1, ...top.map(v => v[sort] ?? 0));
  return <section className="report-dashboard" aria-label="Resultados consultados">
    <div className="report-result-heading"><div><span className="eyebrow">TIKTOK · {data.user.display_name}</span><h2>Tu contenido, en cifras</h2><p>{data.period?.start} — {data.period?.end} · Consulta: {new Date(data.capturedAt).toLocaleString("es-EC")}</p></div><span className="report-source">Datos de la cuenta conectada</span></div>
    {stale && <p role="status" className="report-context-note">Cambiaste el periodo. Pulsa Consultar resultados para actualizar estas cifras.</p>}
    <div className="report-kpis">{[["Videos publicados", data.videos.length, "Dentro del periodo"], ["Visualizaciones", views, "Acumuladas de estos videos"], ["Interacciones", interactions, "Me gusta + comentarios + compartidos"], ["Seguidores", data.user.follower_count, "Total actual de la cuenta"]].map(([name, value, help]) => <div key={String(name)}><span>{name}</span><strong>{fmt(value as number | null)}</strong><small>{help}</small></div>)}</div>
    <p className="report-context-note">El periodo selecciona cuándo se publicaron los videos. Sus visualizaciones e interacciones son acumuladas hasta la consulta, no actividad exclusiva de esas fechas.</p>
    <div className="report-insight-grid"><section className="report-panel"><h2>Cómo interactúa tu audiencia</h2>{[["Me gusta", likes], ["Comentarios", comments], ["Compartidos", shares]].map(([name, value]) => <div className="report-breakdown" key={String(name)}><span>{name}</span><strong>{fmt(value as number | null)}</strong></div>)}<div className="report-breakdown"><span>Interacciones / visualizaciones</span><strong>{views && interactions !== null ? `${(interactions / views * 100).toLocaleString("es", { maximumFractionDigits: 2 })}%` : "No disponible"}</strong></div><p>Esta tasa usa visualizaciones, no alcance de personas únicas.</p></section>
    <section className="report-panel"><h2>Videos con mejores resultados</h2><label>Ordenar por<select value={sort} onChange={e => setSort(e.target.value as typeof sort)}><option value="view_count">Visualizaciones</option><option value="like_count">Me gusta</option><option value="comment_count">Comentarios</option><option value="share_count">Compartidos</option></select></label>{top.map((v, i) => <div className="report-rank" key={v.id}><span>{i + 1}. {(v.title || "Video sin título").slice(0, 65)}</span><strong>{fmt(v[sort])}</strong><meter min={0} max={max} value={v[sort] ?? 0} aria-label={`Resultado del video ${i + 1}`} /></div>)}{!top.length && <p>No hay videos para mostrar.</p>}</section></div>
    <section className="report-panel"><div className="report-result-heading"><div><h2>Explora las publicaciones</h2><p>{ranked.length} de {data.videos.length} videos</p></div><label>Buscar publicación<input type="search" value={search} onChange={e => setSearch(e.target.value)} placeholder="Busca por texto del video" /></label></div><div className="report-table-wrap" tabIndex={0} role="region" aria-label="Tabla de publicaciones"><table className="report-results-table"><thead><tr>{["Publicación", "Fecha", "Vistas", "Me gusta", "Comentarios", "Compartidos"].map(s => <th scope="col" key={s}>{s}</th>)}</tr></thead><tbody>{ranked.map(v => <tr key={v.id}><td><details><summary>{(v.title || "Video sin título").slice(0, 90)}{v.title?.length > 90 ? "…" : ""}</summary><p>{v.title || "Sin descripción"}</p></details></td><td>{v.create_time ? new Date(v.create_time * 1000).toLocaleDateString("es-EC", { timeZone: "America/Guayaquil" }) : "No disponible"}</td>{(["view_count", "like_count", "comment_count", "share_count"] as const).map(k => <td key={k}>{fmt(v[k])}</td>)}</tr>)}</tbody></table></div>{!ranked.length && <p>No hay publicaciones que coincidan.</p>}</section>
    <details className="report-panel"><summary>Qué datos todavía no están disponibles</summary><p>Alcance, demografía, visitas al perfil y seguidores ganados o perdidos del periodo no están disponibles con esta conexión. No se estiman ni se sustituyen por ceros.</p></details>
  </section>;
}
